In [1]:
print("all ok")

all ok


## OHE - One Hot Encoding

In [2]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [10]:

documents = ["people watch movie", 
             "people watch cricket", 
             "people like movie", 
             "people like cricket"]

In [13]:
tokens = [sentence.lower().split() for sentence in documents]
print(tokens)

[['people', 'watch', 'movie'], ['people', 'watch', 'cricket'], ['people', 'like', 'movie'], ['people', 'like', 'cricket']]


In [14]:
all_words = [[word] for sentence in tokens for word in sentence]
print(all_words)

[['people'], ['watch'], ['movie'], ['people'], ['watch'], ['cricket'], ['people'], ['like'], ['movie'], ['people'], ['like'], ['cricket']]


sparse_output=False means the encoder returns a NumPy array instead of a sparse matrix. This makes the output easier

In [15]:
encoder = OneHotEncoder(sparse_output=False)
encoder.fit(all_words)
encoder.categories_

[array(['cricket', 'like', 'movie', 'people', 'watch'], dtype=object)]

In [24]:
print(encoder.categories_[0])
for sentence in tokens:
    encoded_sentence = encoder.transform([[word] for word in sentence])
    print("\nSentence:", sentence)
    print(encoded_sentence)

['cricket' 'like' 'movie' 'people' 'watch']

Sentence: ['people', 'watch', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]

Sentence: ['people', 'watch', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]

Sentence: ['people', 'like', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

Sentence: ['people', 'like', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


## BOW - Bag of Words

In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
documents = ["people watch movie and watch movie again", 
             "people watch cricket and watch cricket",
             "people like movie and like movie a lot",
             "people like cricket"]

In [ ]:
bow = CountVectorizer()


In [10]:
bow_matrix =bow .fit_transform(documents)
print("Vocabulary\n",bow.get_feature_names_out())
print("BOW Matrix:\n", bow_matrix.toarray())

Vocabulary
 ['again' 'and' 'cricket' 'like' 'lot' 'movie' 'people' 'watch']
BOW Matrix:
 [[1 1 0 0 0 2 1 2]
 [0 1 2 0 0 0 1 2]
 [0 1 0 2 1 2 1 0]
 [0 0 1 1 0 0 1 0]]


## TF-IDF

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
documents = ["people watch movie and watch movie again", 
             "people watch cricket and watch cricket",
             "people like movie and like movie a lot",
             "people like cricket"]

In [13]:
tf_idf = TfidfVectorizer()

In [14]:
tf_idf_vector = tf_idf.fit_transform(documents)

In [15]:
print("Vocabulary:", tf_idf.get_feature_names_out())

Vocabulary: ['again' 'and' 'cricket' 'like' 'lot' 'movie' 'people' 'watch']


In [16]:
print("TF-IDF Matrix:\n", tf_idf_vector.toarray())

TF-IDF Matrix:
 [[0.38771136 0.24747114 0.         0.         0.         0.61135218
  0.20232387 0.61135218]
 [0.         0.2684707  0.66322944 0.         0.         0.
  0.21949239 0.66322944]
 [0.         0.24747114 0.         0.61135218 0.38771136 0.61135218
  0.20232387 0.        ]
 [0.         0.         0.64043405 0.64043405 0.         0.
  0.42389674 0.        ]]


# Embedding

## Word2Vec
* The model is trained over google news data
* Dimension of model (number of neurons in hidden layer) = 300

In [1]:
from gensim.models import Word2Vec,KeyedVectors
import gensim.downloader as api

In [2]:
#skim gram
model = api.load("word2vec-google-news-300")

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [3]:
man_embedding = model['man']
print("Dimension of man embedding:", len(man_embedding))
print("man embedding:\n", man_embedding)

Dimension of man embedding: 300
man embedding:
 [ 0.32617188  0.13085938  0.03466797 -0.08300781  0.08984375 -0.04125977
 -0.19824219  0.00689697  0.14355469  0.0019455   0.02880859 -0.25
 -0.08398438 -0.15136719 -0.10205078  0.04077148 -0.09765625  0.05932617
  0.02978516 -0.10058594 -0.13085938  0.001297    0.02612305 -0.27148438
  0.06396484 -0.19140625 -0.078125    0.25976562  0.375      -0.04541016
  0.16210938  0.13671875 -0.06396484 -0.02062988 -0.09667969  0.25390625
  0.24804688 -0.12695312  0.07177734  0.3203125   0.03149414 -0.03857422
  0.21191406 -0.00811768  0.22265625 -0.13476562 -0.07617188  0.01049805
 -0.05175781  0.03808594 -0.13378906  0.125       0.0559082  -0.18261719
  0.08154297 -0.08447266 -0.07763672 -0.04345703  0.08105469 -0.01092529
  0.17480469  0.30664062 -0.04321289 -0.01416016  0.09082031 -0.00927734
 -0.03442383 -0.11523438  0.12451172 -0.0246582   0.08544922  0.14355469
 -0.27734375  0.03662109 -0.11035156  0.13085938 -0.01721191 -0.08056641
 -0.00708

In [4]:
model.most_similar("man")

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116)]

In [5]:
model.most_similar("google")

[('google.com', 0.6711485981941223),
 ('google_yahoo', 0.6488178968429565),
 ('wikipedia', 0.643608033657074),
 ('www.google.com', 0.6258559226989746),
 ('googled', 0.6166064143180847),
 ('googling', 0.6086059212684631),
 ('slashdot', 0.5964587330818176),
 ('lifehacker', 0.5948858857154846),
 ('gizmodo', 0.5884420275688171),
 ('inurl', 0.5882638692855835)]

In [10]:
# Finding similarity between words

print("Similarity between 'king' and 'queen':", model.similarity("king", "queen"))
print("Similarity between 'king' and 'man':", model.similarity("king", "man"))
print("Similarity between 'boy' and 'door':", model.similarity("boy", "door"))
print("Similarity between 'king' and king':", model.similarity("king", "king"))

Similarity between 'king' and 'queen': 0.6510957
Similarity between 'king' and 'man': 0.22942673
Similarity between 'boy' and 'door': 0.12048607
Similarity between 'king' and king': 1.0


In [11]:
# Finding odd one out in a list of words
model.doesnt_match(["PHP","JAVA","DOG","C++"])

'DOG'

In [12]:
# Doing arthmetic operations on word embeddings
vector = model['king'] - model['man'] + model['woman']
model.most_similar([vector], topn=5)

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916)]

In [16]:
# Embedding of a sentence is calculated by averaging the embeddings of all the words in the sentence.

sentence = "people watch movie and watch movie again"
words = sentence.lower().split()
print("Words in the sentence:", words)
word_embeddings = [model[word] for word in words if word in model]
print("dimension of each word embedding:", len(word_embeddings[0]))

Words in the sentence: ['people', 'watch', 'movie', 'and', 'watch', 'movie', 'again']
dimension of each word embedding: 300


In [18]:
import numpy as np
sentence_vector =  np.mean(word_embeddings, axis=0)
print("Embedding of the sentence:\n", sentence_vector)

Embedding of the sentence:
 [ 0.11930338 -0.00775146 -0.00262451  0.261556   -0.12761433  0.01729329
  0.01013184 -0.00565592  0.12005106  0.04661052 -0.01826986 -0.20572917
 -0.06193749 -0.01520793 -0.15673828  0.12268066  0.02335612  0.11604818
 -0.07409668 -0.10880534  0.04361979  0.11149088  0.08243815  0.01957194
  0.06269836 -0.09114584  0.05249023  0.06689453  0.03718058 -0.01883952
 -0.18717448  0.05118815 -0.17293294 -0.02893066  0.04663086 -0.10087077
  0.04732259 -0.01560466 -0.01656087  0.14152019  0.13893636 -0.07454427
  0.19685872 -0.04199219 -0.13979594  0.08703613 -0.03519694 -0.02377319
  0.1185201  -0.03710938 -0.04516602 -0.03942871 -0.00651042  0.10766602
  0.05334473 -0.22526042 -0.0719808  -0.08901978 -0.0324707   0.03105036
 -0.00323486  0.08732096 -0.1044108   0.09396362 -0.0550944   0.10083008
 -0.11572266  0.07747396  0.19069417 -0.01989746 -0.01538086  0.06766764
  0.05244954  0.01814779 -0.09000651 -0.08398438  0.02294922  0.02229818
  0.0709757   0.0371704

In [20]:
# The words which are out of vacabularhy will be failed to get the embedding
model['apple']
model['ChatGPT']  # This will raise a KeyError since 'ChatGPT' is not in the model's vocabulary

KeyError: "Key 'ChatGPT' not present"